#  Build and push Docker image on PR to main

name: Build and Push Docker Image
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: ./.github/workflows/configure-aws.yml
        secrets: inherit
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build Docker image
        run: docker build -t ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/myapp:${{ github.sha }} .
        
      - name: Push Docker image
        run: |
          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/myapp:${{ github.sha }}
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
          
      - name: Save image tag
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ env.IMAGE_TAG }}" > image_tag.txt
          
      - name: Upload image tag
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: image-tag
          path: image_tag.txt