name: Deploy to EKS
on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build-push
    environment: production
    steps:
      - uses: actions/checkout@v3
      
      - name: Download image tag
        uses: actions/download-artifact@v3
        with:
          name: image-tag
          
      - name: Get image tag
        id: image-tag
        run: |
          IMAGE_TAG=$(cat image_tag.txt)
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          
      - name: Configure AWS Credentials
        uses: ./.github/workflows/configure-aws.yml
        secrets: inherit
        
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Install Helm
        uses: azure/setup-helm@v3
        
      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name myapp-eks \
            --region ${{ secrets.AWS_REGION }}
            
      - name: Deploy with Helm
        run: |
          helm upgrade --install myapp ./charts/myapp \
            --namespace myapp \
            --set image.tag=${{ env.IMAGE_TAG }} \
            --atomic \
            --wait