name: Deploy to EKS

on:
  workflow_call:
    inputs:
      aws_role_arn:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      eks_cluster_name:
        required: true
        type: string
      ecr_repository:
        required: true
        type: string
      image_tag:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws_role_arn }}
          aws-region: ${{ inputs.aws_region }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ inputs.eks_cluster_name }} --region ${{ inputs.aws_region }}
      
      - name: Deploy to EKS
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          kubectl set image deployment/myapp myapp=$ECR_REGISTRY/${{ inputs.ecr_repository }}:$IMAGE_TAG 
          
      - name: Helm Charts
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ inputs.image_tag}}
        run: |
          helm upgrade --install myapp ./chart/myapp \
            --set image.repository=${ECR_REGISTRY}/${{ inputs.ecr_repository }} \
            --set image.tag=${IMAGE_TAG} \
            --namespace default \
            --create-namespace


# deploy helm chart from ../chart/myapp folder to EKS cluster
# use the image tag from the build-and-push job
# use the ECR repository from the login-ecr step
# use the EKS cluster name from the inputs
# use the AWS region from the inputs


# deploy:
#   name: Deploy to EKS
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v4
#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v4
#       with:
#         role-to-assume: ${{ inputs.aws_role_arn }}
#         aws-region: ${{ inputs.aws_region }}  

#     - name: Login to Amazon ECR
#       id: login-ecr
#       uses: aws-actions/amazon-ecr-login@v2 

#     - name: Update kubeconfig
#       run: aws eks update-kubeconfig --name ${{ inputs.eks_cluster_name }} --region ${{ inputs.aws_region }}

#     - name: Deploy to EKS
#       env:
#         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#         IMAGE_TAG: ${{ needs.build-and-push.outputs.image-tag }}
#       run: |
#         helm upgrade --install myapp ./chart/myapp \
#           --set image.repository=${ECR_REGISTRY}/${{ env.ECR_REPOSITORY }} \
#           --set image.tag=${IMAGE_TAG} \
#           --namespace default \
#           --create-namespace