#infra-deploy.yml

name: Infrastructure Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - '.github/workflows/infra-deploy.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - '.github/workflows/infra-deploy.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-plan:
    name: Terraform Plan
    uses: ./.github/workflows/terraform-deploy.yml
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    with:
      working-directory: "./terraform"
      terraform-version: "1.5.0"
    secrets:
      aws-role-arn: arn:aws:iam::099199746132:role/my-eks-cluster-github-actions-role

  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/terraform-deploy.yml
    with:
      working-directory: "./terraform"
      terraform-version: "1.5.0"
    secrets:
      aws-role-arn: arn:aws:iam::099199746132:role/my-eks-cluster-github-actions-role