name: Infrastructure Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-infra:
    uses: ./.github/workflows/terraform.yml
    with:
      terraform-dir: "./terraform"
      tf-version: "1.5.0"
    secrets:
      AWS_IAM_ROLE: ${{ secrets.AWS_IAM_ROLE }}
      AWS_REGION: ${{ secrets.AWS_REGION }}