name: Main CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      aws_role_arn:
        description: 'AWS Role ARN'
        required: false
        type: string
      aws_region:
        description: 'AWS Region'
        required: false
        type: string
      eks_cluster_name:
        description: 'EKS Cluster Name'
        required: false
        type: string
      ecr_repository:
        description: 'ECR Repository Name'
        required: false
        type: string
      terraform_version:
        description: 'Terraform Version'
        required: false
        type: string
      java_version:
        description: 'Java Version'
        required: false
        type: string

jobs:
  deploy-infrastructure:
    name: Deploy Infrastructure
    uses: ./.github/workflows/infra-deploy.yml
    with:
      aws_role_arn: ${{ inputs.aws_role_arn || vars.AWS_ROLE_ARN }}
      aws_region: ${{ inputs.aws_region || vars.AWS_REGION }}
      terraform_version: ${{ inputs.terraform_version || vars.TERRAFORM_VERSION }}
    permissions:
      id-token: write
      contents: read

  test:
    name: Test Application
    needs: deploy-infrastructure
    uses: ./.github/workflows/test.yml
    with:
      java_version: ${{ inputs.java_version || vars.JAVA_VERSION }}
    permissions:
      id-token: write
      contents: read

  build-and-push:
    name: Build and Push Docker Image
    needs: test
    uses: ./.github/workflows/build-push.yml
    with:
      aws_role_arn: ${{ inputs.aws_role_arn || vars.AWS_ROLE_ARN }}
      aws_region: ${{ inputs.aws_region || vars.AWS_REGION }}
      ecr_repository: ${{ inputs.ecr_repository || vars.ECR_REPOSITORY }}
    permissions:
      id-token: write
      contents: read

  deploy-application:
    name: Deploy Application to EKS
    needs: build-and-push
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    uses: ./.github/workflows/deploy.yml
    with:
      aws_role_arn: ${{ inputs.aws_role_arn || vars.AWS_ROLE_ARN }}
      aws_region: ${{ inputs.aws_region || vars.AWS_REGION }}
      eks_cluster_name: ${{ inputs.eks_cluster_name || vars.EKS_CLUSTER_NAME }}
      ecr_repository: ${{ inputs.ecr_repository || vars.ECR_REPOSITORY }}
      image_tag: ${{ needs.build-and-push.outputs.image_tag }} 
    permissions:
      id-token: write
      contents: read 