name: CI-CD-Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: production
  cancel-in-progress: true

env:
  ECR_REPOSITORY: myapp
  EKS_CLUSTER_NAME: my-cluster
  TERRAFORM_VERSION: 1.5.0

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infrastructure:
    name: Deploy Infrastructure
    uses: ./.github/workflows/infra-deploy.yml
    with:
      aws_role_arn: ${{ vars.AWS_ROLE_ARN }}
      aws_region: ${{ vars.AWS_REGION }}
      terraform_version: ${{ env.TERRAFORM_VERSION }}
    secrets: inherit

  build-and-push:
    name: Build and Push Docker Image
    needs: deploy-infrastructure
    uses: ./.github/workflows/build-push.yml
    with:
      aws_role_arn: ${{ vars.AWS_ROLE_ARN }}
      aws_region: ${{ vars.AWS_REGION }}
      ecr_repository: ${{ env.ECR_REPOSITORY }}
    secrets: inherit

  deploy-application:
    name: Deploy Application
    needs:
      - build-and-push
      - deploy-infrastructure
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: production
      url: https://your-production-url.com
    if: ${{ success() }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Kubernetes and Helm configurations
        uses: actions/cache@v4
        with:
          path: |
            ~/.kube
            ~/.helm
          key: ${{ runner.os }}-k8s-${{ hashFiles('**/*.yaml') }}
          restore-keys: |
            ${{ runner.os }}-k8s-

      - name: Deploy Application to EKS
        run: |
          chmod +x .github/scripts/deploy.sh
          .github/scripts/deploy.sh \
            "${{ vars.AWS_ROLE_ARN }}" \
            "${{ vars.AWS_REGION }}" \
            "${{ env.EKS_CLUSTER_NAME }}" \
            "${{ env.ECR_REPOSITORY }}" \
            "${{ needs.build-and-push.outputs.image_tag }}"

      - name: Health Check
        if: success()
        run: echo "Performing health check..."

      - name: Notify Deployment Status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const status = '${{ job.status }}';
            const message = `Deployment to production ${status}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: message
            });
