# Terraform plan/apply for infrastructure changes
# This workflow is triggered on pull requests and pushes to the main branch
name: Terraform Reusable Workflow
on: workflow_call

inputs:
  terraform-dir:
    description: 'Directory containing Terraform configuration'
    required: true
    default: './terraform'
  tf-version:
    description: 'Terraform version to use'
    required: false
    default: '1.5.0'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production
  
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: ./.github/workflows/configure-aws.yml
        secrets: inherit
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.tf-version }}
          
      # Terraform Linting
      - name: Install tflint
        uses: terraform-linters/setup-tflint@v2
        with:
          tflint_version: v0.47.0
          
      - name: Run tflint
        run: |
          tflint --init
          tflint --module --enable-rule=terraform_documented_variables \
                 --enable-rule=terraform_documented_outputs \
                 --enable-rule=terraform_typed_variables \
                 --enable-rule=terraform_naming_convention \
                 --enable-rule=terraform_unused_declarations
        working-directory: ${{ inputs.terraform-dir }}  

      # Checkov Security Scanning
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ${{ inputs.terraform-dir }}
          framework: terraform
          quiet: true
          soft_fail: false
          download_external_modules: true
          skip_check: CKV_AWS_115,CKV_AWS_111 # Example of checks to skip
          
      # Continue with existing steps
      - name: Terraform Format
        run: terraform fmt -check -recursive
        working-directory: ${{ inputs.terraform-dir }}
        continue-on-error: true
      
      - name: Terraform Init
        run: terraform init -input=false
        working-directory: ${{ inputs.terraform-dir }}
        continue-on-error: true
        
      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ inputs.terraform-dir }}
        
      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan
        working-directory: ${{ inputs.terraform-dir }}
        continue-on-error: true
        
      - name: Terraform Plan Status
        if: failure()
        run: exit 1
        
      - name: Upload Terraform Plan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: ${{ inputs.terraform-dir }}/tfplan
          
      - name: Approve Plan
        if: github.event_name == 'pull_request'
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: ${{ env.APPROVERS }}
          
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -input=false tfplan
        working-directory: ${{ inputs.terraform-dir }}