name: Terraform Reusable Workflow

on:
  workflow_call:
    inputs:
      terraform-dir:
        description: 'Directory containing Terraform configuration'
        required: true
        default: './terraform'
      tf-version:
        description: 'Terraform version to use'
        required: false
        default: '1.5.0'
    secrets:
      AWS_IAM_ROLE:
        required: true
      AWS_REGION:
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.tf-version }}
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHubActions-${{ github.run_id }}
          
      - name: Terraform Init
        run: terraform init -input=false
        working-directory: ${{ inputs.terraform-dir }}
        
      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ inputs.terraform-dir }}
        
      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan
        working-directory: ${{ inputs.terraform-dir }}
        
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: ${{ inputs.terraform-dir }}/tfplan
          
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -input=false tfplan
        working-directory: ${{ inputs.terraform-dir }}