name: Terraform Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        default: 'production'
        type: choice
        options:
          - production
      confirmation:
        description: 'Type "destroy" to confirm'
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  actions: write  # Needed for policy detachment

env:
  TERRAFORM_VERSION: '1.5.0'
  TF_WORKING_DIR: 'terraform'

jobs:
  terraform-destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    environment: production
    
    if: github.event.inputs.confirmation == 'destroy'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Terraform directory exists
        run: |
          if [ ! -d "${{ env.TF_WORKING_DIR }}" ]; then
            echo "::error::Terraform directory '${{ env.TF_WORKING_DIR }}' not found"
            ls -la
            exit 1
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -no-color

      - name: Detach IAM Policies
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          # Get list of all IAM policies in state
          terraform state list | grep 'aws_iam_policy\.' | while read -r POLICY; do
            echo "Processing $POLICY"
            
            # Get policy ARN (compatible with all Terraform versions)
            ARN=$(terraform state show "$POLICY" | grep -m 1 'arn:' | awk '{print $3}' | tr -d '"')
            
            if [ -n "$ARN" ]; then
              echo "Detaching policy with ARN: $ARN"
              
              # Detach from roles
              ROLES=$(aws iam list-entities-for-policy --policy-arn "$ARN" --query 'PolicyRoles[].RoleName' --output text 2>/dev/null || true)
              if [ -n "$ROLES" ]; then
                for ROLE in $ROLES; do
                  echo "Detaching from role: $ROLE"
                  aws iam detach-role-policy --role-name "$ROLE" --policy-arn "$ARN" || true
                done
              fi
              
              # Detach from users
              USERS=$(aws iam list-entities-for-policy --policy-arn "$ARN" --query 'PolicyUsers[].UserName' --output text 2>/dev/null || true)
              if [ -n "$USERS" ]; then
                for USER in $USERS; do
                  echo "Detaching from user: $USER"
                  aws iam detach-user-policy --user-name "$USER" --policy-arn "$ARN" || true
                done
              fi
            else
              echo "Could not extract ARN for policy: $POLICY"
            fi
          done

      - name: Terraform Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          if terraform state list >/dev/null 2>&1; then
            echo "Resources found - proceeding with destroy"
            
            # First attempt with lock
            if terraform destroy -auto-approve -no-color; then
              echo "Destroy completed successfully"
            else
              echo "First attempt failed, retrying with lock disabled"
              terraform destroy -auto-approve -no-color -lock=false
            fi
          else
            echo "No resources in state - nothing to destroy"
          fi